# FROM sys-base:latest
FROM team14registry.azurecr.io/sys-base:latest

ENV RPC_ADDRESS=127.0.0.1
ENV RPC_PORT=50051
ENV BLOB_CONNECTION="YOUR_AZURE_BLOB_KEY"
ENV FAIL=0
# Define the rest of your dockerfile here

RUN rm -rf build
RUN rm -rf CMake*

RUN mkdir -p /sys-dir
COPY ./ sys-dir/

RUN cd sys-dir && rm -rf build && mkdir build && cd build \
    && cmake .. && make -j4

WORKDIR /sys-dir/build
EXPOSE 50051
ENTRYPOINT [ "./worker" ]
